### ISSUE TITLE
model

### ISSUE THREAD

**Issue by lyc-lang** [ChengBinJin/MRI-to-CT-DCNN-TensorFlow#2]
The link here cannot be downloaded to the trained VGG16 model weights. Could you please send me a copy?  `mirror_whut@qq.com` Thank you

**Comment by ChengBinJin** [comment]
@lyc-lang 
This field is more than 1.5GB, so I think I can't send you by email. 
I'm tried to diagnose your problem. But the link seems to work good. I just downloaded it just few minutes ago. Can you try it again?

**Comment by lyc-lang** [comment]
Many thanks，I have worked it out in another way.

**Comment by lyc-lang** [comment]
As you said that you have implemented a cross validation with Corresponding coefficient k = 6
, but I found in your dataset.py code `self.train_data = [item for sub_block in blocks for item in sub_block] + \filenames[-np.mod(len(filenames), num_cross_vals):]`，In this case, train_data overlaps with val_data and test_data when the data set is partitioned as you do. Any questions here？

**Comment by ChengBinJin** [comment]
@lyc-lang 
DCNN model is trained several times and each time the model uses different separations of the train, validation, and test. Therefore, they are not overlapped. The variable, `idx_cross_val` plays an essential role to control different validation and test.

**Comment by lyc-lang** [comment]
I am sorry to disturb you again.
I know what you mean, however, when I took 10 files to test result, for example,I take k =5,`Dataset('brain01', 5, 0)` .the outcome shows the result that test_data = [0, 1],  val_data = [2, 3], train_data =[4,5,6,7,8,9,0,1,2,3,4,5,6,7,8,9](each number represents a file name).Then I make a change by `self.train_data = [item for sub_block in blocks for item in sub_block]`,and get result as test_data = [0, 1],  val_data = [2, 3], train_data =[4,5,6,7,8,9], So is there a little bit of a flaw in the code here?

**Comment by ChengBinJin** [comment]
@lyc-lang 
Yes, you are right. The `+filenames[-np.mod(len(filenames), num_cross_val):]` wants to use the remaining data if the number of data can't divide by the number of blocks correctly. In your experiments, If you have 11 files and 5 blocks, then simply ignoring the above code can't use the last data file.

The bug if fixed as the following:

<p align='center'>
  <img src="https://user-images.githubusercontent.com/37034031/65828726-b6d90500-e2d8-11e9-8dcb-5e711caf84bf.png" width=600)
</p>  

Thank you for your careful testing.

**Comment by lyc-lang** [comment]
In that case, the outcome of data separation  is right. Thank you for reminding me！

**Comment by zichao999** [comment]
The link here cannot be downloaded to the trained VGG16 model weights. Could you please send me a copy? 79808121@qq.com Thank you

**Comment by lyc-lang** [comment]
I'm sorry！I can't send u now，maybe I could give u a copy in the next few weeks if I can have access to the internet.&nbsp;



---Original---

**Comment by ChengBinJin** [comment]
@zichao999 
Hi, you can find the pretrained VGG model from the following link (https://yunpan.360.cn/surl_yxLDnu6QqjQ (password:3ouy)

**Comment by Yangshuo732** [comment]
@lyc-lang The link here cannot be downloaded to the trained VGG16 model weights. Could you please send me a copy? [3517162165@qq.com](mailto:3517162165@qq.com) Thank you!
